### ISSUE TITLE
求一个暗色主题

### ISSUE THREAD

**Issue by zhlicen** [RichardLuo0/vscode-frosted-glass-theme#1]
浅色对比度太高
![image](https://user-images.githubusercontent.com/3927021/97098677-b87f2300-16ba-11eb-99cb-8e998896c57b.png)

**Comment by RichardLuo0** [comment]
到设置里找到frosted-glass-theme.backgroundColor，换成你喜欢的颜色，然后ctrl+shift+p，运行update frosted glass theme，根据提示重启即可

**Comment by zhlicen** [comment]
get
