### ISSUE TITLE
[BUG] Not working properly with Fluent UI for VSCode

### ISSUE THREAD

**Issue by Lukoning** [RichardLuo0/vscode-frosted-glass-theme#10]
**Describe the bug**
Some background doesn't work or is abnormal
The Settings menu is cropped (Why?)
Animation works

**To Reproduce**
1. Install both Frosted Glass Theme and Fluent UI for VSCode
2. Enable Frosted Glass Theme, reload
3. Enable or reload Fluent UI for VSCode
4. Open any context menu

**Expected behavior**
Try to fix them

**Screenshots**
When Fluent UI disabled:
![屏幕截图 2024-08-08 114352](https://github.com/user-attachments/assets/78a01af5-1d8a-4e0d-826f-f98662dd1cc6)

When enabled:
![屏幕截图 2024-08-08 114527](https://github.com/user-attachments/assets/be9dd300-86ef-4055-8eaf-8483919e9a03)
![屏幕截图 2024-08-08 114819](https://github.com/user-attachments/assets/05e5c039-c06b-4923-be6b-f4df23062a8f)
![屏幕截图 2024-08-08 114545](https://github.com/user-attachments/assets/0b693a26-7754-4395-854b-6596b90dec36)
![屏幕截图 2024-08-08 115115](https://github.com/user-attachments/assets/b014a391-65e2-4d5b-8826-c71380c4c399)
![屏幕截图 2024-08-08 115853](https://github.com/user-attachments/assets/bff29206-8976-49fd-af0b-39f15b495784)

**Version (please complete the following information):**
 - OS:  Windows 11 (22631.3958)
 - VSCode version: 1.92.0
 - Extension version: v0.7.11
 
![image](https://github.com/user-attachments/assets/ad09c50a-dced-4fac-a90d-0492f91dc2f4)

**Comment by Lukoning** [comment]
Append screenshots

![屏幕截图 2024-08-08 130413](https://github.com/user-attachments/assets/1addff54-3058-44d2-9ccf-94c2720f468f)
![屏幕截图 2024-08-08 130443](https://github.com/user-attachments/assets/5f6d9ee8-5727-47fd-beb7-3bf72d8fd13d)
![屏幕截图 2024-08-08 130519](https://github.com/user-attachments/assets/59ab0237-f713-43c3-8a5a-6886ccd0c5f9)

**Comment by RichardLuo0** [comment]
Hi can you try go to `C:\Users\<username>\.vscode\extensions\leandro-rodrigues.fluent-ui-vscode-3.9.0\out\css\editor_chrome.css` and delete `backdrop-filter: var(--backdrop-filter);` and `background: whatever he sets` under  `.context-view.monaco-menu-container`, then disable and re-enable fluent UI.
You may be aware that fluent ui has its own acrylic implementation but from what I can tell, fluent UI's acrylic will not work correctly on submenu because of [this](https://github.com/RichardLuo0/vscode-frosted-glass-theme/blob/a1af8bc6262a3533a8f003273410d2753a749620/src-inject/fix.ts#L21). And its broken implementation will affect my extension unfortunately.

**Comment by RichardLuo0** [comment]
In fact, I suggest removing every backdrop-filter that fluent UI sets. They are mostly duplicated with my extension. That being said, it is up to you which one you want to use.

**Comment by Lukoning** [comment]
I remove all backdrop-filter and do something like this:
![image](https://github.com/user-attachments/assets/5c14bd3e-5fe1-4293-98e2-09b949fe8623)

Now all context menu effects are normal, except for one that looks like a glow.
![image](https://github.com/user-attachments/assets/382eb712-ccb7-48c3-b670-f8a4203df1eb)

**Comment by RichardLuo0** [comment]
Search for `.action-item:hover` and try to remove all `background` properties

**Comment by Lukoning** [comment]
![屏幕截图 2024-08-09 012447](https://github.com/user-attachments/assets/fd3ca89b-edcf-487a-a24b-1e1b5479e517)
![屏幕截图 2024-08-09 012459](https://github.com/user-attachments/assets/9ab58569-5119-42ca-bb3c-a60b8dc0da6c)

THANKS!

![image](https://github.com/user-attachments/assets/101c4e24-a7e1-4fc6-b8bc-4af1649d4f00)

**Comment by RichardLuo0** [comment]
Remember you can change reveal effect color through `menu.selectionBackground` in `workbench.colorCustomizations`

**Comment by Lukoning** [comment]
...Sorry to bother you again
It might be tricky, can the anomaly in this place be fixed?

![image](https://github.com/user-attachments/assets/cb30d1c8-f9dd-45ff-bc62-b0742140d4b9)

And I wanna know how to debug VSCode itself
This way I can easily solve some problems by myself

**Comment by RichardLuo0** [comment]
> And I wanna know how to debug VSCode itself This way I can easily solve some problems by myself

Open "developer tools" from help menu. 
Use this tool:
![image](https://github.com/user-attachments/assets/9af8a2ca-0b95-4020-86dd-51562657c0d3)
Select the element you need and check for its properties

**Comment by RichardLuo0** [comment]
You can also right click on elements and set breakpoint on modifications

**Comment by Lukoning** [comment]
Got it, thank you🙏🙏🙏

**Comment by RichardLuo0** [comment]
> ...Sorry to bother you again It might be tricky, can the anomaly in this place be fixed?
> 
> ![image](https://private-user-images.githubusercontent.com/92252063/356325294-cb30d1c8-f9dd-45ff-bc62-b0742140d4b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxNDA5MTAsIm5iZiI6MTcyMzE0MDYxMCwicGF0aCI6Ii85MjI1MjA2My8zNTYzMjUyOTQtY2IzMGQxYzgtZjlkZC00NWZmLWJjNjItYjA3NDIxNDBkNGI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDE4MTAxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmMTc2Mjg1MGQ1YWExMmY3MWFmYWI2ZTMwNDc1ZWZiZDExZGE2ZGFiODU1ZTVkMDZjNmQ0NGJiMDI0OTA0NTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4A4PUpIn_ok3lCc7PUIXhXTChJpVN61252T5QW8fNgA)
> 
> And I wanna know how to debug VSCode itself This way I can easily solve some problems by myself

This is a tricky one. It looks like fluent ui creates stacking context somewhere. It will take a lot of time to pinpoint the root.
I am tired of debugging fluent ui 😥. I suggest you just use either my extension or fluent UI alone. Note that fluent ui hasn't been updated for over a year.

**Comment by Lukoning** [comment]
> > ...Sorry to bother you again It might be tricky, can the anomaly in this place be fixed?．．．很抱歉再次打扰你，可能会很棘手，这个地方的异常可以修复吗?
> > ![image](https://private-user-images.githubusercontent.com/92252063/356325294-cb30d1c8-f9dd-45ff-bc62-b0742140d4b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxNDA5MTAsIm5iZiI6MTcyMzE0MDYxMCwicGF0aCI6Ii85MjI1MjA2My8zNTYzMjUyOTQtY2IzMGQxYzgtZjlkZC00NWZmLWJjNjItYjA3NDIxNDBkNGI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDE4MTAxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmMTc2Mjg1MGQ1YWExMmY3MWFmYWI2ZTMwNDc1ZWZiZDExZGE2ZGFiODU1ZTVkMDZjNmQ0NGJiMDI0OTA0NTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4A4PUpIn_ok3lCc7PUIXhXTChJpVN61252T5QW8fNgA)
> > And I wanna know how to debug VSCode itself This way I can easily solve some problems by myself我想知道如何调试VSCode本身，这样我就可以很容易地自己解决一些问题
> 
> This is a tricky one. It looks like fluent ui creates stacking context somewhere. It will take a lot of time to pinpoint the root.这是一个棘手的问题。看起来流畅的ui在某个地方创建了堆叠上下文。要找出根源要花很多时间。 I am tired of debugging fluent ui 😥. I suggest you just use either my extension or fluent UI alone. Note that fluent ui hasn't been updated for over a year.我厌倦了调试流畅的ui😥。我建议你只使用我的扩展或流畅的UI单独。请注意，fluent ui已经有一年多没有更新了。

👌

**Comment by Lukoning** [comment]
> > ...Sorry to bother you again It might be tricky, can the anomaly in this place be fixed?
> > ![image](https://private-user-images.githubusercontent.com/92252063/356325294-cb30d1c8-f9dd-45ff-bc62-b0742140d4b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxNDA5MTAsIm5iZiI6MTcyMzE0MDYxMCwicGF0aCI6Ii85MjI1MjA2My8zNTYzMjUyOTQtY2IzMGQxYzgtZjlkZC00NWZmLWJjNjItYjA3NDIxNDBkNGI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDE4MTAxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmMTc2Mjg1MGQ1YWExMmY3MWFmYWI2ZTMwNDc1ZWZiZDExZGE2ZGFiODU1ZTVkMDZjNmQ0NGJiMDI0OTA0NTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4A4PUpIn_ok3lCc7PUIXhXTChJpVN61252T5QW8fNgA)
> > And I wanna know how to debug VSCode itself This way I can easily solve some problems by myself
> 
> This is a tricky one. It looks like fluent ui creates stacking context somewhere. It will take a lot of time to pinpoint the root. I am tired of debugging fluent ui 😥. I suggest you just use either my extension or fluent UI alone. Note that fluent ui hasn't been updated for over a year.

👌
