### ISSUE TITLE
[BUG] Source Control view menu is not shown, and the loading progress bar is not on the top

### ISSUE THREAD

**Issue by yakamoz423** [RichardLuo0/vscode-frosted-glass-theme#11]
**Describe the bug**
First of all, thank you for your extension! In recent use, I found:

1. Source Control view menu is not shown
It was just recently encountered. See the video. Other menus are fine.

2. The loading progress bar is not on the top
This is a long-standing issue. The progress bar has been blurred.

**Screenshots**

https://github.com/user-attachments/assets/d2ce3d10-3715-4f0c-a177-50b08df38181

**Version (please complete the following information):**
 - OS: Windows 11 build 22631
 - VSCode version: 1.92.1
 - Extension version: v0.7.12

**Comment by RichardLuo0** [comment]
> 1. Source Control view menu is not shown
>    It was just recently encountered. See the video. Other menus are fine.

Oops... My mistake. It will be fixed soon

**Comment by RichardLuo0** [comment]
> The loading progress bar is not on the top
> This is a long-standing issue. The progress bar has been blurred.

Which one do you prefer?

![image](https://github.com/user-attachments/assets/feec1ba3-ac68-448e-9e25-2e69486f6fdc)

![image](https://github.com/user-attachments/assets/dc1df7b1-f7c6-4679-a427-5cb7ae90b0b6)

**Comment by yakamoz423** [comment]
> > The loading progress bar is not on the top
> > This is a long-standing issue. The progress bar has been blurred.
> 
> Which one do you prefer?
> 
> ![image](https://private-user-images.githubusercontent.com/22096448/357302898-feec1ba3-ac68-448e-9e25-2e69486f6fdc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1MzIwODEsIm5iZiI6MTcyMzUzMTc4MSwicGF0aCI6Ii8yMjA5NjQ0OC8zNTczMDI4OTgtZmVlYzFiYTMtYWM2OC00NDhlLTllMjUtMmU2OTQ4NmY2ZmRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDA2NDk0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmMTQ3YzRkZjBkOWQ3MDRiODU2OGRmNDYwZWE5YTg4YWMwM2YzODI1YTAwZDE4MjU5M2EwYTdmYmIyOWFhNjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aqShNHelI7-H-6vUQf84FocKWQBz5li0Jd0p9XXc3dw)
> 
> ![image](https://private-user-images.githubusercontent.com/22096448/357302784-dc1df7b1-f7c6-4679-a427-5cb7ae90b0b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1MzIwODEsIm5iZiI6MTcyMzUzMTc4MSwicGF0aCI6Ii8yMjA5NjQ0OC8zNTczMDI3ODQtZGMxZGY3YjEtZjdjNi00Njc5LWE0MjctNWNiN2FlOTBiMGI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDA2NDk0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExMjczZmUwMzU1ODA1NWFiNzhiYmFiZDk3NzZkNTg2YjEwY2U0OWYzZjcyZTM0N2M4MDA4YzFiZmExZmY1MDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1w8oEF3R9t0hOCufGd730olP7J5VNRqo1ONMJDBKo7o)

I prefer the second one, because the first one is not so obvious.

**Comment by yakamoz423** [comment]
@RichardLuo0 Another bug found😂 The handle on the scroll bar disappears.

![image](https://github.com/user-attachments/assets/5e11a3db-7be0-42f8-98eb-a1f2e3b9d148)

Should be:
![image](https://github.com/user-attachments/assets/e834f4db-6b83-4819-ab29-3235236a533d)

**Comment by RichardLuo0** [comment]
The minimap goes grey because of the luminosity blend. Try change `fgt-mica-luminosity` in `variableDark`, or you just set `filter.minimap` to `blur(30px)`
The original purpose of this design is to make the backdrop to have the same luminosity. But I will reset them to `blur(30px)` in 他the next version.

**Comment by RichardLuo0** [comment]
Try the new version. Should be solved already.

**Comment by yakamoz423** [comment]
> Try the new version. Should be solved already.

I have tried the newer version, there is one more thing. Hover or click state on the scroll bar handle still have no visual effect.

**Comment by RichardLuo0** [comment]
Can you take a screenshot? This should have been fixed

**Comment by yakamoz423** [comment]
> Can you take a screenshot? This should have been fixed

Enabled:

https://github.com/user-attachments/assets/ff98ec4e-3725-4ec9-af68-3f6b6b2e4fbd

Disabled:

https://github.com/user-attachments/assets/69d2b488-fccc-47e0-a210-a2989cc62585

**Comment by RichardLuo0** [comment]
Try the new version
