### ISSUE TITLE
[BUG] text selection shows extra rectangles on ench line left and right when fakeMica is enabled

### ISSUE THREAD

**Issue by yakamoz423** [RichardLuo0/vscode-frosted-glass-theme#13]
**Describe the bug**
"frosted-glass-theme.fakeMica.enabled": false ↓
![image](https://github.com/user-attachments/assets/a94c9d99-5c6a-4a7e-bd7c-783ae31ef8ed)

"frosted-glass-theme.fakeMica.enabled": true ↓
![image](https://github.com/user-attachments/assets/ec51da47-7b01-4e2c-8343-bbf80c4a3278)

Additionally, disable frosted-glass-theme and set "editor.background": "#ffffffdd" ↓
![image](https://github.com/user-attachments/assets/e4a1e151-b318-4e49-b8b3-dc95a768ecb9)
There are similar rectangles, but the color is lighter.

**Version (please complete the following information):**
 - OS: Windows 11 23H2 22631
 - VSCode version: 1.92.2
 - Extension version: 0.8.1

**Comment by RichardLuo0** [comment]
I can fix it, but this small rounded corner is achieved by cropping a `<div>` so I won't be able to keep them.
![image](https://github.com/user-attachments/assets/3d70f84f-bb5c-4b83-a5f0-65af30573670)

**Comment by yakamoz423** [comment]
Awesome! Thank you
