### ISSUE TITLE
[BUG] Cannot be enabled on VS Code 1.94.0.

### ISSUE THREAD

**Issue by MaxLHy0424** [RichardLuo0/vscode-frosted-glass-theme#14]
**Describe the bug**
VS Code can't use this extension after it's updated to 1.94.0 (insider).

**To Reproduce**
1. Go to command panel.
2. Click on '>Frosted Glass Theme: Setup', Then make the default configuration.
3. Click on '>Frosted Glass Theme: Apply Configuration'.
4. Click on '>Frosted Glass Theme: Enable'.
6. See error.

**Expected behavior**
The changes to the extension are applied correctly.

**Screenshots**
![image](https://github.com/user-attachments/assets/8594cb34-6c9d-471d-bbee-faac77d261fb)

**Version (please complete the following information):**
 - OS: Windows 11 Build 27695.1000 (Cannary Channel).
 - VSCode version: 1.94.0-insider
 - Extension version: v0.8.9

**Comment by RichardLuo0** [comment]
Can you open the dev tool from help -> dev tool and take a screenshot of the console?

**Comment by MaxLHy0424** [comment]
> Can you open the dev tool from help -> dev tool and take a screenshot of the console?

OK.

![image](https://github.com/user-attachments/assets/02170f16-6a80-4b80-bb4d-75f1cb9ff6ee)

**Comment by RichardLuo0** [comment]
你发下倒数第二条

**Comment by MaxLHy0424** [comment]
> 你发下倒数第二条

![image](https://github.com/user-attachments/assets/2803205a-1d3f-418a-9956-5bd92fef2cca)

**Comment by RichardLuo0** [comment]
https://1drv.ms/u/s!AvQ5Yi4H3cH9h-MfJEnarr4kb3EwMw?e=cZpb7Y
你试一下这个版本

**Comment by MaxLHy0424** [comment]
> https://1drv.ms/u/s!AvQ5Yi4H3cH9h-MfJEnarr4kb3EwMw?e=cZpb7Y 你试一下这个版本

无法安装
![image](https://github.com/user-attachments/assets/fd3f39d0-3371-4c0a-b188-3628271169d8)

**Comment by RichardLuo0** [comment]
啊？你直接用解压软件打开呢？

**Comment by RichardLuo0** [comment]
> > https://1drv.ms/u/s!AvQ5Yi4H3cH9h-MfJEnarr4kb3EwMw?e=cZpb7Y 你试一下这个版本
> 
> 无法安装 ![image](https://private-user-images.githubusercontent.com/142279449/366531549-fd3f39d0-3371-4c0a-b188-3628271169d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwNzA2NTAsIm5iZiI6MTcyNjA3MDM1MCwicGF0aCI6Ii8xNDIyNzk0NDkvMzY2NTMxNTQ5LWZkM2YzOWQwLTMzNzEtNGMwYS1iMTg4LTM2MjgyNzExNjlkOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMVQxNTU5MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zOGFjYzAzNTYwZmZiMWFiYmMyNGFlYTQ2MGIxODA0NDRjYjFhZWFmYWQzZDlkY2YzNTE3ZDUwOGE5NTFiMWRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.W5fi9wjbcriHthnIOeviwAE0HDtU_3CEifmTKKVCYKM)

vsix实际上就是个压缩包。我怀疑你下载没下完整，重新下载一下试试看？

**Comment by MaxLHy0424** [comment]
> > > https://1drv.ms/u/s!AvQ5Yi4H3cH9h-MfJEnarr4kb3EwMw?e=cZpb7Y 你试一下这个版本
> > 
> > 
> > 无法安装 ![image](https://private-user-images.githubusercontent.com/142279449/366531549-fd3f39d0-3371-4c0a-b188-3628271169d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwNzA2NTAsIm5iZiI6MTcyNjA3MDM1MCwicGF0aCI6Ii8xNDIyNzk0NDkvMzY2NTMxNTQ5LWZkM2YzOWQwLTMzNzEtNGMwYS1iMTg4LTM2MjgyNzExNjlkOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMVQxNTU5MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zOGFjYzAzNTYwZmZiMWFiYmMyNGFlYTQ2MGIxODA0NDRjYjFhZWFmYWQzZDlkY2YzNTE3ZDUwOGE5NTFiMWRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.W5fi9wjbcriHthnIOeviwAE0HDtU_3CEifmTKKVCYKM)
> 
> vsix实际上就是个压缩包。我怀疑你下载没下完整，重新下载一下试试看？

能安装上了, 但还是报错...
![image](https://github.com/user-attachments/assets/9ca3a068-d817-4c86-8465-83a962ca5439)
![image](https://github.com/user-attachments/assets/11b58c9b-b010-4311-90f4-09d15a31cea0)

**Comment by RichardLuo0** [comment]
试一下这个版本 https://1drv.ms/u/s!AvQ5Yi4H3cH9h-Mi77d-JmuI-47Q0A?e=5TgO63

**Comment by MaxLHy0424** [comment]
> 试一下这个版本 https://1drv.ms/u/s!AvQ5Yi4H3cH9h-Mi77d-JmuI-47Q0A?e=5TgO63

已经可以正常使用了!
