### ISSUE TITLE
[BUG] The collapse bar is too small.

### ISSUE THREAD

**Issue by MaxLHy0424** [RichardLuo0/vscode-frosted-glass-theme#16]
**Describe the bug**
The collapse bar is too small when enabled.

**To Reproduce**
1. Go to the command pannel;
2. Click on '>Frosted Glass Theme: Enable';
3. Reboot VS Code;
4. See error.

**Expected behavior**
The size of the collapse bar remains the same.

**Screenshots**
![image](https://github.com/user-attachments/assets/4173448f-992e-4a98-84a4-93678ee7e085)
![image](https://github.com/user-attachments/assets/a4c062d6-bc91-4a29-a66d-94052a1e9534)
![image](https://github.com/user-attachments/assets/4868b0e0-e8bc-45b8-b846-f2f082de2de5)

**Version (please complete the following information):**
 - OS: Windows 11 (Build 27729.1000)
 - VSCode version: 1.94.0-insiders
 - Extension version: v0.8.11

**Comment by RichardLuo0** [comment]
Try adding the following
```css
.pane-header {
  flex-shrink: 0;
}
```
to `C:\Users\<YourUsername>\.vscode-insiders\extensions\richardluo.frosted-glass-theme-0.8.11\inject\vscode-frosted-glass-theme.css` and restart vscode

**Comment by MaxLHy0424** [comment]
> Try adding the following
> 
> ```css
> .pane-header {
>   flex-shrink: 0;
> }
> ```
> 
> to `C:\Users\<YourUsername>\.vscode-insiders\extensions\richardluo.frosted-glass-theme-0.8.11\inject\vscode-frosted-glass-theme.css` and restart vscode

That is OK!
