### ISSUE TITLE
[BUG] The flip effect makes long item hard to click

### ISSUE THREAD

**Issue by yakamoz423** [RichardLuo0/vscode-frosted-glass-theme#17]
I like the new flip effect and reveal effect very much, but there is a small issue.

For an item that is very wide or very long, the flip effect will break its interactivity. It is hard to click buttons on it, as shown in the video.

https://github.com/user-attachments/assets/51b092db-4376-4676-937a-2ee6da984d50

**Comment by RichardLuo0** [comment]
I made some changes to the algorithm. Try the latest version.

**Comment by yakamoz423** [comment]
It fixed! ❤️❤️❤️
