### ISSUE TITLE
[Feature] Rounded highlights in right click menus.

### ISSUE THREAD

**Issue by IdkWhatToCallMe123** [RichardLuo0/vscode-frosted-glass-theme#18]
Is it possible to add something similar to the effect in the second picture?

![圖片](https://github.com/user-attachments/assets/f6e77f02-d172-45bc-8a75-e645fe0dbc07)

![圖片](https://github.com/user-attachments/assets/06046973-d451-424e-8cdb-a98ca1e3377d)

**Comment by RichardLuo0** [comment]
Hi, update to the latest version, try setting `frosted-glass-theme.effect.extendMenuFocusBackground` to false and set `frosted-glass-theme.animation.menuItem` to empty. If you want, you can set `frosted-glass-theme.animation.actionMenuItem` to "fgt-revealEffect, fgt-flipEffect" so you can still get these effects.

**Comment by IdkWhatToCallMe123** [comment]
Awesome!
