### ISSUE TITLE
Adjust the blur of background

### ISSUE THREAD

**Issue by ncwuguo** [RichardLuo0/vscode-frosted-glass-theme#20]
How to adjust the blur of the interface background wallpaper, I did not find the relevant settings in README.

**Comment by RichardLuo0** [comment]
Change `frosted-glass-theme.fakeMica.filter` to anything that can be used in https://developer.mozilla.org/zh-CN/docs/Web/CSS/filter

Or you can add an svg in `frosted-glass-theme.svg` and use it in `frosted-glass-theme.fakeMica.filter`. By default it uses https://github.com/RichardLuo0/vscode-frosted-glass-theme/blob/dev/resource/mica.svg?short_path=95fdc55
