### ISSUE TITLE
Not applying anymore (Frosted Glass theme commands no more found)

### ISSUE THREAD

**Issue by enoversum** [RichardLuo0/vscode-frosted-glass-theme#3]
There was just an update to Frosted Glass Theme, and now neither the settings work, nor can I enable, disable or reload the configuration via commands anymore, it's throwing errors that those commands cannot be found. Is that a known bug?

Also, blur animation did never apply for me, just the semi-transparent background. Left everything as it was, and even tried to change the blur effect in settings.

**Comment by enoversum** [comment]
> This shouldn't happen. Whats your vscode version? Did you happen to install vscode to one of the protected directories (for example, C:\Program Files)?

This wasn't happening until today (commands not found), so I suspect the new update to be the culprit. VS Code on Windows installs itself to `C:\Users\<username>\Appdata\Local\Programs\Microsoft VS Code`. I'm on 1.85.2, latest update.

**Comment by enoversum** [comment]
> Do you remember when the extension was first installed? I am pretty sure the 0.7.1 update touches nothing about the extension part. Btw, can you go to help > open developer tools, then go to console and check if there are any errors?

Yes, I do remember. I installed it last week, without the glitch concerning commands not being available. 
Thanks for the tip regarding console errors. There are a few for another one (not related), but this one shows for your current one. I had already tried to reinstall it, to no avail. Seems a crucial file is missing :) .

`Activating extension 'RichardLuo.frosted-glass-theme' failed: Cannot find module 'c:\Users\xxx\.vscode\extensions\richardluo.frosted-glass-theme-0.7.1\out\extension.js'
Require stack:
- c:\Users\xxx\appdata\local\programs\microsoft vs code\resources\app\out\vs\loader.js
- c:\Users\xxx\appdata\local\programs\microsoft vs code\resources\app\out\bootstrap-amd.js
- c:\Users\xxx\appdata\local\programs\microsoft vs code\resources\app\out\bootstrap-fork.js
- .`

**Comment by RichardLuo0** [comment]
this is weird... Can you confirm the `C:\Users\xxx\.vscode\extensions\richardluo.frosted-glass-theme-0.7.1\out\extension.js` is missing? Try to download the latest file [here](https://marketplace.visualstudio.com/items?itemName=RichardLuo.frosted-glass-theme) and install via extension > more > install from VSIX.
You mentioned the blur effect is not working, is the animation not working too?

**Comment by enoversum** [comment]
> this is weird... Can you confirm the `C:\Users\xxx\.vscode\extensions\richardluo.frosted-glass-theme-0.7.1\out\extension.js` is missing? Try to download the latest file from version history [here](https://marketplace.visualstudio.com/items?itemName=RichardLuo.frosted-glass-theme) and install via extension > more > install from VSIX. You mentioned the blur effect is not working, is the animation not working too?

Yes, I can confirm that in version 0.7.1, the file is missing: There's the whole `out` folder missing:

![image](https://github.com/RichardLuo0/vscode-frosted-glass-theme/assets/8190174/6e93a8f3-678f-4241-b06f-52a9e7902894)

What would the animation look like? At this point, there is no animation whatsoever, since the extension isn't working ;) .

**Comment by enoversum** [comment]
Update: I uninstalled your extension, then deleted both extension folders manually, then re-installed. All files are there as needed now, so the extension (including animation) is working now. Just not the blur effect ;) .

**Comment by RichardLuo0** [comment]
Good to hear. I see you are using another extension to change the window background to use mica or acrylic material, unfortunately, there is currently no way to apply both effect https://github.com/electron/electron/issues/30412 ,   sorry you have to make a choice

**Comment by enoversum** [comment]
> Good to hear. I see you are using another extension to change the window background to use mica or acrylic material, unfortunately, there is currently no way to apply both effect [electron/electron#30412](https://github.com/electron/electron/issues/30412) , sorry you have to make a choice

That's Vibrancy, which changes a lot, but not right-click menu backgrounds. So you suggest that I use either one of these extensions, and the other one being active probably results in the blur effect not applying? Otherwise, your extension was working flawlessly up to today :) .

**Comment by RichardLuo0** [comment]
I know vibrancy doesn't change menu background. The point is, as long as window background remains acrylic (even transparent!), all blur on web are gone. [Electron document](https://www.electronjs.org/docs/latest/tutorial/window-customization#limitations). There is nothing I can do. Though if you can change electron source code, it might be possible, but that is way beyond this extension

**Comment by enoversum** [comment]
Thanks for confirming what the trouble is with the blur effect. I'd have loved to combine both extensions for a more complete feeling, but I understand it's not fully possible to do so. Have a nice day :) !

**Comment by RichardLuo0** [comment]
> Thanks for confirming what the trouble is with the blur effect. I'd have loved to combine both extensions for a more complete feeling, but I understand it's not fully possible to do so. Have a nice day :) !
Hi, I am not sure if you are still using my extension, but anyway I have developed a fake mica feature that mimics the feel of Windows 11 mica effects. If you are interested in this feature, follow the readme to enable fake mica.

**Comment by enoversum** [comment]
> > Thanks for confirming what the trouble is with the blur effect. I'd have loved to combine both extensions for a more complete feeling, but I understand it's not fully possible to do so. Have a nice day :) !
> 
> Hi, I am not sure if you are still using my extension, but anyway I have developed a fake mica feature that mimics the feel of Windows 11 mica effects. If you are interested in this feature, follow the readme to enable fake mica.

Thanks, @RichardLuo0 , for picking up my issue again. Because Vibrancy, which had clashed with your extension, did never really look stunning in its style, and because it brought up more problems than it brought pleasure, I recently uninstalled it, so your extension is working with 'real' Mica just fine. But good to know you implemented a workaround, in case I want to use both extensions in the future again.
