### ISSUE TITLE
[BUG] Sticky line characters overlapped unrecognizable

### ISSUE THREAD

**Issue by cylixlee** [RichardLuo0/vscode-frosted-glass-theme#4]
Hi Richard, thank you for creating such a beautiful extension! Frosted glass just comforts me a lot. However there's something going wrong with the newly introduced VSCode feature "**sticky line**".
 
**Describe the bug**
Sticky lines are shown when viewing a very large function or a scoped block thing. For example, here's what I'm working on:

![image](https://github.com/RichardLuo0/vscode-frosted-glass-theme/assets/153902646/60653fce-40f1-4c9d-b4a6-38334d3d7e96)

There's a `Bytecode` class and a method named `FromExisting`. Both the class and the method have a large scope so those two sticky lines are shown. But when I scroll down a little bit, it will be look like this:

![image](https://github.com/RichardLuo0/vscode-frosted-glass-theme/assets/153902646/214e6b69-20c7-4fe4-8e62-907462773629)

I guess VSCode just simply renders the two sticky lines at one place when I scrolled because of simplicity. That works when frost-grass is not applied because the normal sticky lines are opaque. Things are different when transparency is applied.

So it there any way to apply Glass Effect (I don't know what exactly what it is, Mica, Blur or something) above the underlying sticky line(s)? Doing so shall solve the problem.

**Comment by RichardLuo0** [comment]
I tried setting blur effects behind each line, then this happens:
![image](https://github.com/RichardLuo0/vscode-frosted-glass-theme/assets/22096448/50a09c25-8cfd-43e1-abb8-3523e0a053df)

**Comment by cylixlee** [comment]
Ah, i didn't expect that...  Treating the underlying sticky lines as the blur target (same as the code) may be the right solution, but I can imagine how hard it is...

**Comment by RichardLuo0** [comment]
I am sorry, I can't think of any reasonable way to fix this. Any help will be appreciated.
