### ISSUE TITLE
[BUG] Error on Linux

### ISSUE THREAD

**Issue by kb-ig** [RichardLuo0/vscode-frosted-glass-theme#6]
**Describe the bug**
Hitting an error when trying `Frosted Glass Theme: Enable` on Linux;

>Something went wrong: Error:
Command failed: cd "/home/my-user"; export ELECTRON_RUN_AS_NODE="1"; "/usr/bin/pkexec" --disable-internal-agent /bin/bash -c "echo SUDOPROMPT; ELECTRON_RUN_AS_NODE=1 \"/usr/share/code/code\" --ms-enable-electron-run-as-node \"/home/my-user/.vscode/extensions/richardluo.frosted-glass-theme-0.7.4/out/InjectionAdminMain.js\" --no-sandbox inject \"[{\\\"_path\\\":\\\"/home/my-user/.vscode/extensions/richardluo.frosted-glass-theme-0.7.4/inject/vscode-frosted-glass-theme.js\\\"}]\" \"/usr/share/code/resources/app/out/vs/code\" \"/usr/share/code/resources/app/out/vs/code/electron-sandbox/workbench/workbench.html\"" /usr/share/code/code: bad option: --ms-enable-electron-run-as-node

It looks like it's not happy with the `--ms-enable-electron-run-as-node` arg. Note that when I start VSCode from the terminal and pass in this arg, I get a warning, but VSCode still runs

```
code --ms-enable-electron-run-as-node
Warning: 'ms-enable-electron-run-as-node' is not in the list of known options, but still passed to Electron/Chromium.

```

**To Reproduce**
1. Install extension
2. Enable via command palette 
3. Click on prompt for admin credentials - enter credentials

**Expected behavior**
I expect that after applying the credentials the theme should be enabled.

**Screenshots**

**Version (please complete the following information):**
 - OS: Zorin OS 17.1
 - VSCode version:
```
 Version: 1.88.1
Commit: e170252f762678dec6ca2cc69aba1570769a5d39
Date: 2024-04-10T17:34:12.840Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Linux x64 6.5.0-27-generic
```
 - Extension version: 0.7.4

**Comment by RichardLuo0** [comment]
If you remove the `--ms-enable-electron-run-as-node` and run in terminal, does it work?

**Comment by RichardLuo0** [comment]
Can you please try the newest release? I should have fixed it.

**Comment by RichardLuo0** [comment]
Hi since you did not reply, I assume it has been solved. I will close the issue, feel free to reopen.

**Comment by kb-ig** [comment]
@RichardLuo0 Apologies for the delay. The latest update did fix the installation and this error is no longer present. I now receive another notification, however:
> Your Code installation appears to be corrupt. Please reinstall

![image](https://github.com/RichardLuo0/vscode-frosted-glass-theme/assets/91877080/fc0b2ed8-1604-4644-a4d6-ace5d23fa283)

As far as I can tell, everything is working OK, so I'm not sure exactly what this notification is referring to.

**Comment by RichardLuo0** [comment]
That is completely normal. The notification is actually from vscode, meaning that workbench.html is modified, which is exactly how this extension works.
