### ISSUE TITLE
[BUG] Submenu issue

### ISSUE THREAD

**Issue by ToothyJarl** [RichardLuo0/vscode-frosted-glass-theme#8]
**Describe the bug**
When hovering over something with submenus, for example File, the submenu will not open and seems to go into the previous menu.

**To Reproduce**
1. Click on File a few times.

**Expected behavior**
A submenu should be opened.

**Screenshots**
![image](https://github.com/user-attachments/assets/99585f04-4626-4947-9585-ff3ec277103e)
![image](https://github.com/user-attachments/assets/58cc3932-5f27-4518-a251-915423bddf7c)

**Version (please complete the following information):**
 - OS: Windows 11
 - VSCode version: 1.91.1
 - Extension version: v0.7.6

**Comment by RichardLuo0** [comment]
Will be fixed soon

**Comment by RichardLuo0** [comment]
Try with the new version. Should have been fixed.
