### ISSUE TITLE
[Feature] Add a Mica-style background by sampling the wallpaper

### ISSUE THREAD

**Issue by yakamoz423** [RichardLuo0/vscode-frosted-glass-theme#9]
Just like [Fluent UI for VSCode](https://marketplace.visualstudio.com/items?itemName=leandro-rodrigues.fluent-ui-vscode)?

**Comment by RichardLuo0** [comment]
The latest version includes this feature! However, there are unfortunately many bugs, so it's not enabled by default, follow the readme to enable it.

**Comment by yakamoz423** [comment]
Thanks for your quick response! But after setting `"frosted-glass-theme.fakeMica.enabled": true`, The title bar has become gray, and background is still pure.😭

![image](https://github.com/user-attachments/assets/fd6cf874-6cfa-49b5-ad6e-5c4578a774f0)

Extension: v0.7.9
Version: 1.92.0 (system setup)
Commit: b1c0a14de1414fcdaa400695b4db1c0799bc3124
Date: 2024-07-31T23:26:45.634Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631

**Comment by yakamoz423** [comment]
If anyone sees black blocks on terminal after changing `panel.background` or `terminal.background`, turning off the `terminal.integrated.gpuAcceleration` will solve this.

![image](https://github.com/user-attachments/assets/711fcc94-717e-46a7-92ba-d59f092f3011)
